/**
 * Exhaustive per-type slot schemas for `metadata.slots` (string values).
 * Group titles are for UI sections only.
 */

import type { TypeViewConfig } from './elementSlotsTypes'

const g = (group: string) => group

export const ELEMENT_TYPE_VIEWS: Record<string, TypeViewConfig> = {
  Idea: {
    contentLabel: 'Body',
    contentPlaceholder:
      'Free-form narrative: expand the spark, variants, and anything not captured in slots below.',
    slots: [
      { key: 'working_title', label: 'Working title', group: g('Identity') },
      { key: 'one_line_spark', label: 'One-line spark', multiline: true, group: g('Identity') },
      { key: 'problem_or_tension', label: 'Problem or tension', multiline: true, group: g('Framing') },
      { key: 'intended_audience', label: 'Intended audience', group: g('Framing') },
      { key: 'medium_or_format', label: 'Medium / format', placeholder: 'novel, short, game, pitch…', group: g('Framing') },
      { key: 'genre_tags', label: 'Genre tags', placeholder: 'comma-separated mood tags', group: g('Framing') },
      { key: 'central_question', label: 'Central question', multiline: true, group: g('Framing') },
      { key: 'status', label: 'Status', placeholder: 'draft, incubating, parked, rejected…', group: g('Lifecycle') },
      { key: 'priority', label: 'Priority', placeholder: 'low / medium / high', group: g('Lifecycle') },
      { key: 'next_action', label: 'Next action', multiline: true, group: g('Lifecycle') },
      { key: 'dependencies_notes', label: 'Dependencies on other elements', multiline: true, group: g('Lifecycle') },
      { key: 'success_criteria', label: 'Success criteria', multiline: true, group: g('Quality') },
      { key: 'non_goals', label: 'Explicit non-goals', multiline: true, group: g('Quality') },
      { key: 'risks_and_unknowns', label: 'Risks and unknowns', multiline: true, group: g('Quality') },
      { key: 'references_inspirations', label: 'References & inspirations', multiline: true, group: g('References') },
      { key: 'competing_ideas', label: 'Competing ideas to reconcile', multiline: true, group: g('References') },
      { key: 'hook_for_pitch', label: 'Hook for pitch / logline draft', multiline: true, group: g('Pitch') },
      { key: 'open_threads', label: 'Open threads to revisit', multiline: true, group: g('Pitch') },
    ],
  },

  Character: {
    contentLabel: 'Body',
    contentPlaceholder: 'Long-form biography, scenes, voice samples, and prose not stored in slots.',
    slots: [
      { key: 'display_name', label: 'Display name', group: g('Identity') },
      { key: 'aliases', label: 'Aliases / codenames', group: g('Identity') },
      { key: 'role_in_story', label: 'Role in story', placeholder: 'protagonist, mentor, foil…', group: g('Identity') },
      { key: 'age_band', label: 'Age band', placeholder: 'child, 30s, immortal…', group: g('Identity') },
      { key: 'species_or_kind', label: 'Species / kind', group: g('Identity') },
      { key: 'pronouns', label: 'Pronouns', group: g('Identity') },
      { key: 'occupation', label: 'Occupation', group: g('Identity') },
      { key: 'appearance_overview', label: 'Appearance overview', multiline: true, group: g('Appearance') },
      { key: 'face_and_gaze', label: 'Face & gaze', multiline: true, group: g('Appearance') },
      { key: 'hair', label: 'Hair', multiline: true, group: g('Appearance') },
      { key: 'body_and_stature', label: 'Body & stature', multiline: true, group: g('Appearance') },
      { key: 'wardrobe_signature', label: 'Wardrobe signature', multiline: true, group: g('Appearance') },
      { key: 'distinguishing_marks', label: 'Distinguishing marks', multiline: true, group: g('Appearance') },
      { key: 'voice_accent', label: 'Voice — accent & language', group: g('Voice') },
      { key: 'voice_tone', label: 'Voice — tone & pacing', multiline: true, group: g('Voice') },
      { key: 'voice_vocabulary', label: 'Voice — vocabulary & ticks', multiline: true, group: g('Voice') },
      { key: 'personality_summary', label: 'Personality summary', multiline: true, group: g('Psychology') },
      { key: 'core_desire', label: 'Core desire', multiline: true, group: g('Psychology') },
      { key: 'core_fear', label: 'Core fear', multiline: true, group: g('Psychology') },
      { key: 'moral_compass', label: 'Moral compass', multiline: true, group: g('Psychology') },
      { key: 'contradictions', label: 'Internal contradictions', multiline: true, group: g('Psychology') },
      { key: 'skills_and_limits', label: 'Skills & limits', multiline: true, group: g('Psychology') },
      { key: 'relationships_overview', label: 'Relationships overview', multiline: true, group: g('Social') },
      { key: 'family_and_origin', label: 'Family & origin', multiline: true, group: g('Social') },
      { key: 'faction_affiliations', label: 'Faction / affiliations', multiline: true, group: g('Social') },
      { key: 'secrets', label: 'Secrets', multiline: true, group: g('Social') },
      { key: 'backstory_origin', label: 'Backstory — formative origin', multiline: true, group: g('Backstory') },
      { key: 'backstory_turning_point', label: 'Backstory — turning point', multiline: true, group: g('Backstory') },
      { key: 'arc_want', label: 'Arc — want', multiline: true, group: g('Narrative arc') },
      { key: 'arc_need', label: 'Arc — need', multiline: true, group: g('Narrative arc') },
      { key: 'arc_change', label: 'Arc — change by end', multiline: true, group: g('Narrative arc') },
      { key: 'entrance_and_exit', label: 'Entrance & exit conditions', multiline: true, group: g('Narrative arc') },
      { key: 'casting_notes', label: 'Casting / performance notes', multiline: true, group: g('Production') },
      { key: 'ref_visual_notes', label: 'Reference art notes', multiline: true, group: g('Production') },
    ],
  },

  Scene: {
    contentLabel: 'Body',
    contentPlaceholder: 'Full scene prose, blocking, and dialogue not captured in slots.',
    slots: [
      { key: 'scene_label', label: 'Scene label', placeholder: 'INT/EXT, slug line…', group: g('Header') },
      { key: 'location_name', label: 'Location name', multiline: true, group: g('Space') },
      { key: 'location_type', label: 'Location type', placeholder: 'interior, exterior, vehicle…', group: g('Space') },
      { key: 'geography_notes', label: 'Geography & layout', multiline: true, group: g('Space') },
      { key: 'time_of_day', label: 'Time of day', group: g('Time') },
      { key: 'timeframe_story', label: 'Story timeframe', placeholder: 'day 3, flashback…', group: g('Time') },
      { key: 'duration_estimate', label: 'Duration estimate', group: g('Time') },
      { key: 'weather', label: 'Weather / atmosphere', group: g('Atmosphere') },
      { key: 'lighting', label: 'Lighting', multiline: true, group: g('Atmosphere') },
      { key: 'color_palette', label: 'Color palette', group: g('Atmosphere') },
      { key: 'soundscape', label: 'Soundscape', multiline: true, group: g('Atmosphere') },
      { key: 'mood', label: 'Mood', multiline: true, group: g('Atmosphere') },
      { key: 'pov', label: 'Point of view', group: g('Narration') },
      { key: 'tense', label: 'Tense', group: g('Narration') },
      { key: 'beats_outline', label: 'Beats outline', multiline: true, group: g('Structure') },
      { key: 'turning_beat', label: 'Turning beat', multiline: true, group: g('Structure') },
      { key: 'props_key', label: 'Key props', multiline: true, group: g('Staging') },
      { key: 'characters_present', label: 'Characters present', multiline: true, group: g('Staging') },
      { key: 'blocking_notes', label: 'Blocking notes', multiline: true, group: g('Staging') },
      { key: 'continuity_notes', label: 'Continuity notes', multiline: true, group: g('Production') },
      { key: 'vfx_notes', label: 'VFX / practical notes', multiline: true, group: g('Production') },
      { key: 'costume_notes', label: 'Costume / makeup notes', multiline: true, group: g('Production') },
    ],
  },

  Story: {
    contentLabel: 'Body',
    contentPlaceholder: 'Synopsis, beat sheets, and prose drafts.',
    slots: [
      { key: 'logline', label: 'Logline', multiline: true, group: g('Pitch') },
      { key: 'title_options', label: 'Title options', multiline: true, group: g('Pitch') },
      { key: 'genre', label: 'Genre', group: g('Pitch') },
      { key: 'tone', label: 'Tone', multiline: true, group: g('Pitch') },
      { key: 'theme', label: 'Theme', multiline: true, group: g('Theme') },
      { key: 'thematic_question', label: 'Thematic question', multiline: true, group: g('Theme') },
      { key: 'central_conflict', label: 'Central conflict', multiline: true, group: g('Conflict') },
      { key: 'antagonistic_forces', label: 'Antagonistic forces', multiline: true, group: g('Conflict') },
      { key: 'stakes', label: 'Stakes', multiline: true, group: g('Conflict') },
      { key: 'structure_model', label: 'Structure model', placeholder: 'three-act, five-act, spiral…', group: g('Structure') },
      { key: 'act_breakdown', label: 'Act breakdown', multiline: true, group: g('Structure') },
      { key: 'midpoint', label: 'Midpoint', multiline: true, group: g('Structure') },
      { key: 'climax_notes', label: 'Climax notes', multiline: true, group: g('Structure') },
      { key: 'resolution_notes', label: 'Resolution notes', multiline: true, group: g('Structure') },
      { key: 'subplots', label: 'Subplots', multiline: true, group: g('Threads') },
      { key: 'foreshadowing', label: 'Foreshadowing & payoffs', multiline: true, group: g('Threads') },
      { key: 'world_rules', label: 'World rules', multiline: true, group: g('World') },
      { key: 'audience', label: 'Audience', group: g('Market') },
      { key: 'comparable_titles', label: 'Comparable titles', multiline: true, group: g('Market') },
      { key: 'status', label: 'Status', group: g('Process') },
      { key: 'revision_notes', label: 'Revision notes', multiline: true, group: g('Process') },
      { key: 'open_questions', label: 'Open questions', multiline: true, group: g('Process') },
    ],
  },

  Script: {
    contentLabel: 'Body',
    contentPlaceholder: 'Full screenplay or script text.',
    slots: [
      { key: 'format_standard', label: 'Format standard', placeholder: 'Fountain, US stage, custom…', group: g('Format') },
      { key: 'revision_color', label: 'Revision color / ID', group: g('Format') },
      { key: 'page_target', label: 'Page / length target', group: g('Format') },
      { key: 'scene_numbering', label: 'Scene numbering scheme', group: g('Structure') },
      { key: 'scene_outline_ref', label: 'Scene outline reference', multiline: true, group: g('Structure') },
      { key: 'dialogue_style', label: 'Dialogue style guide', multiline: true, group: g('Style') },
      { key: 'stage_directions_style', label: 'Stage / action line style', multiline: true, group: g('Style') },
      { key: 'character_voice_notes', label: 'Character voice notes (global)', multiline: true, group: g('Style') },
      { key: 'music_and_sound_cues', label: 'Music & sound cues policy', multiline: true, group: g('Audio') },
      { key: 'vfx_annotations', label: 'VFX annotation policy', multiline: true, group: g('Production') },
      { key: 'revision_notes', label: 'Revision notes', multiline: true, group: g('Revision') },
      { key: 'table_read_notes', label: 'Table read notes', multiline: true, group: g('Revision') },
      { key: 'coverage_notes', label: 'Coverage / feedback summary', multiline: true, group: g('Revision') },
      { key: 'legal_clearance', label: 'Legal / clearance notes', multiline: true, group: g('Compliance') },
    ],
  },

  Storyboard: {
    contentLabel: 'Body',
    contentPlaceholder: 'Sequence intent, mood boards, and notes not in shots.',
    slots: [
      { key: 'aspect_ratio', label: 'Aspect ratio', placeholder: 'e.g. 2.39:1', group: g('Format') },
      { key: 'resolution_target', label: 'Resolution target', group: g('Format') },
      { key: 'frame_rate', label: 'Frame rate', group: g('Format') },
      { key: 'color_pipeline', label: 'Color pipeline / LUT notes', group: g('Look') },
      { key: 'visual_style', label: 'Visual style keywords', multiline: true, group: g('Look') },
      { key: 'reference_films', label: 'Reference films / boards', multiline: true, group: g('Look') },
      { key: 'sequence_intent', label: 'Sequence intent', multiline: true, group: g('Narrative') },
      { key: 'pacing_notes', label: 'Pacing notes', multiline: true, group: g('Narrative') },
      { key: 'transition_policy', label: 'Transitions policy', multiline: true, group: g('Narrative') },
      { key: 'audio_stems_plan', label: 'Audio stems plan', multiline: true, group: g('Audio') },
      { key: 'notes', label: 'General notes', multiline: true, group: g('Notes') },
      { key: 'review_status', label: 'Review status', group: g('Process') },
    ],
  },

  Shot: {
    contentLabel: 'Body',
    contentPlaceholder: 'Shot description, motion, and audio.',
    slots: [
      { key: 'shot_code', label: 'Shot code', placeholder: 'e.g. 12A', group: g('Header') },
      { key: 'duration_sec', label: 'Duration (seconds)', group: g('Header') },
      { key: 'camera_angle', label: 'Camera angle', group: g('Camera') },
      { key: 'camera_height', label: 'Camera height', group: g('Camera') },
      { key: 'lens_mm', label: 'Lens (mm)', group: g('Camera') },
      { key: 'movement', label: 'Camera movement', multiline: true, group: g('Camera') },
      { key: 'framing', label: 'Framing', multiline: true, group: g('Camera') },
      { key: 'focus_policy', label: 'Focus policy', group: g('Camera') },
      { key: 'screen_direction', label: 'Screen direction / axis', group: g('Staging') },
      { key: 'eyeline', label: 'Eyeline notes', multiline: true, group: g('Staging') },
      { key: 'blocking', label: 'Blocking', multiline: true, group: g('Staging') },
      { key: 'lighting_setup', label: 'Lighting setup', multiline: true, group: g('Lighting') },
      { key: 'time_of_day', label: 'Time of day (shot)', group: g('Lighting') },
      { key: 'production_design', label: 'Production design notes', multiline: true, group: g('Art') },
      { key: 'vfx_notes', label: 'VFX notes', multiline: true, group: g('VFX') },
      { key: 'dialogue', label: 'Dialogue / VO', multiline: true, group: g('Audio') },
      { key: 'sfx', label: 'SFX', multiline: true, group: g('Audio') },
      { key: 'music', label: 'Music', multiline: true, group: g('Audio') },
      { key: 'edit_notes', label: 'Edit notes', multiline: true, group: g('Post') },
    ],
  },
  Collection: {
    contentLabel: 'Bundle notes',
    contentPlaceholder: 'Optional narrative about how you use this collection.',
    slots: [
      { key: 'collection_purpose', label: 'Purpose', multiline: true, group: g('Identity') },
      { key: 'notes', label: 'Notes', multiline: true, group: g('Notes') },
    ],
  },
}
